name: Release-Build-Dev

on:
  workflow_dispatch:
  push:
    branches:
      - feature/MARP-4636-introduce-nightly-release-builds

permissions:
  contents: read
  actions: read
  packages: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/release-dev.yml@feature/MARP-4636-introduce-nightly-release-builds

